### ISSUE TITLE
bad print statement

### ISSUE THREAD

**Issue by jalwood** [gehaxelt/Python-dsstore#1]
I apologize, I just do a little scripting for work, I don't know how to use git to do this myself but when I tried to run this script I would get this error:
```

Traceback (most recent call last):
  File "C:\Tools\ds_store_python\Python-dsstore-master\main.py", line 1, in <module>
    import dsstore
  File "C:\Tools\ds_store_python\Python-dsstore-master\dsstore.py", line 117
    print("[DEBUG] ", *args)
                      ^
SyntaxError: invalid syntax
```

I changed line 117 to:

`print("[DEBUG] {}".format(*args))`

and it ran successfully.  Just wanted to report it to you so it can be fixed

**Comment by gehaxelt** [comment]
@jalwood Thanks for the hint! I've made a change - Mind having a look at the PR?
